stages:
- build
- deploy

variables:
  GL_IMAGE_NAME: $CI_REGISTRY/kugoo109/$CI_PROJECT_NAME
  GL_IMAGE_TAG: $CI_COMMIT_SHA

build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $GL_IMAGE_NAME:$GL_IMAGE_TAG .
  - docker push $GL_IMAGE_NAME:$GL_IMAGE_TAG

deploy:
  stage: deploy
  script:
  - kubectl config set-cluster my-cluster --server=$KUBE_URL --insecure-skip-tls-verify=true
  - kubectl config set-credentials admin --token=$KUBE_TOKEN
  - kubectl config set-context my-context --cluster=my-cluster --user=admin --namespace=$KUBE_NAMESPACE
  - kubectl config use-context my-context
  - kubectl apply -f ./deploy/node-app-pod.yaml
  - kubectl apply -f ./deploy/node-app-service.yaml