stages:
- build
- deploy

variables:
  GL_IMAGE_NAME: $CI_REGISTRY/kugoo109/$CI_PROJECT_NAME
  GL_IMAGE_TAG: CI_PIPELINE_ID

build:
  stage: build
  image: docker:ding
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $GL_IMAGE_NAME:$GL_IMAGE_TAG .
  - docker push $GL_IMAGE_NAME:$GL_IMAGE_TAG

deploy:
  stage: deploy
  environment:
    name: staging
  image: appuio/gitlab-runner-oc:latest
  script:
  - oc config set-cluster my-cluster --server=$KUBE_URL
  - oc config set-credentials admin --token=$KUBE_TOKEN
  - oc config set-context my-context --cluster=my-cluster --user=admin --namespace=$KUBE_NAMESPACE
  - oc config use-context my-context
  - /bin/sh deploy/deploy_to_cluster.sh $GL_IMAGE_TAG