apiVersion: v1
kind: Service
metadata:
  name: node-deployment
spec:
  selector:
    app: node-deployment
  ports:
  - name: web
    protocol: TCP
    port: 8888
    targetPort: 3000
  type: LoadBalancer
  
