apiVersion: v1
kind: Pod
metadata:
  name: node-deployment
  labels:
    app: "node-deployment"
spec:
  containers:
  - name: node-deployment
    image: registry.gitlab.com/kugoo109/node-deployment:v1
    ports:
    - containerPort: 3000
  imagePullSecrets:
    - name: regsecret
